id                       
rcount                   
gender                   
dialysisrenalendstage    
asthma                   
irondef                  
pneum                    
substancedependence      
psychologicaldisordermajo
depress                  
psychother               
fibrosisandother         
malnutrition             
hemo                     
hematocrit               
neutrophils              
sodium                   
glucose                  
bloodureanitro           
creatinine               
bmi                      
pulse                    
respiration              
secondarydiagnosisnonicd9
facid               